#import mysql.connector as sql
#mydb=sql.connect(host="localhost",user="root",passwd="admin123",database="SMS")
from tkinter import *
from tkinter import ttk
def insert ():
    c=mydb.cursor()
    Form = Tk()
    Form.fontsize=26
    Form.geometry('600x500')
    heading=Label(Form,text='Student form ',font=('Arial',12,'bold'),bg='white')
    #______________________main_________________________________
    label_r=Label(Form,text='Roll No: ',font=('Arial',12,'bold'),bg='white')
    label_n=Label(Form,text='Name:',font=('Arial',12,'bold'),bg='white')
    label_c=Label(Form,text='Class: ',font=('Arial',12,'bold'),bg='white')
    label_add=Label(Form,text='Adress: ',font=('Arial',12,'bold'),bg='white')
    label_d=Label(Form,text='D.O.B: ',font=('Arial',12,'bold'),bg='white')
    label_g=Label(Form,text='Gender: ',font=('Arial',12,'bold'),bg='white')
    label_co=Label(Form,text='Contact No: ',font=('Arial',12,'bold'),bg='white')
    label_e=Label(Form,text='Email id: ',font=('Arial',12,'bold'),bg='white')
    label_s=Label(Form,text='Stream: ',font=('Arial',12,'bold'),bg='white')
    #__________________________________father_____________________________________
    label_f=Label(Form,text="Father's Name: ",font=('Arial',12,'bold'),bg='white')
    #________________________________Mother____________________________________________
    label_m=Label(Form,text="Mother's Name:" ,font=('Arial',12,'bold'),bg='white')
    #_______________________________position________________________________________________
    heading.pack()
    label_r.place(x=1,y=20)
    label_n.place(x=1,y=60)
    label_c.place(x=1,y=100)
    label_f.place(x=1,y=140)
    label_m.place(x=1,y=180)
    label_add.place(x=1,y=220)
    label_d.place(x=1,y=260)
    label_g.place(x=1,y=300)
    label_co.place(x=1,y=340)
    label_e.place(x=1,y=380)
    label_s.place(x=1,y=420)
    #_________________________________________________________________________________________
    r=IntVar()
    n=StringVar()
    c=StringVar()
    f=StringVar()
    m=StringVar()
    add=StringVar()
    d=StringVar()
    g=StringVar()
    co=IntVar()
    e=StringVar()
    s=StringVar()
    def save():
        ce=mydb.cursor()
        rn=r.get()
        ename=n.get()
        eclass=c.get()
        fname=f.get()
        mname=m.get()
        addi=add.get()
        dob=d.get()
        sex=g.get()
        con=co.get()
        email=e.get()
        stream=s.get()
        r.set("")
        n.set("")
        c.set("")
        f.set("")
        m.set("")
        add.set("")
        g.set("")
        d.set("")
        co.set("")
        e.set("")
        s.set("")
        #query="INSERT INTO STUDENT values({},'{}','{}','{}','{}','{}','{}','{}',{},'{}','{}')".format(rn,ename,eclass,fname,mname,addi,dob,sex,con,email,stream)
        #ce.execute(query)
        #mydb.commit()
    def clear():
        r.set("")
        n.set("")
        c.set("")
        f.set("")
        m.set("")
        add.set("")
        g.set("")
        d.set("")
        co.set("")
        e.set("")
        s.set("")
    input_r=Entry(Form,width=5,bd=8,textvariable=r)
    input_n=Entry(Form,width=20,bd=8,textvariable=n)
    input_c=Entry(Form,width=20,bd=8,textvariable=c)
    input_f=Entry(Form,width=20,bd=8,textvariable=f)
    input_m=Entry(Form,width=20,bd=8,textvariable=m)
    input_add=Entry(Form,width=50,bd=8,textvariable=add)
    input_male=Radiobutton(Form,text='Male',variable=g,value='M')
    input_female=Radiobutton(Form,text='Female',variable=g,value='F')
    input_d=Entry(Form,width=50,bd=8,textvariable=d)      
    input_co=Entry(Form,width=20,bd=8,textvariable=co)
    input_e=Entry(Form,width=20,bd=8,textvariable=e)
    input_s=Entry(Form,width=20,bd=8,textvariable=s)
    input_r.place(x=100,y=20)
    input_n.place(x=100,y=60)
    input_c.place(x=100,y=100)
    input_f.place(x=120,y=140)
    input_m.place(x=120,y=180)
    input_add.place(x=100,y=220)
    input_d.place(x=100,y=260)
    input_male.place(x=100,y=300)
    input_female.place(x=200,y=300)
    input_co.place(x=100,y=340)
    input_e.place(x=100,y=380)
    input_s.place(x=100,y=420)
    #__________________________Button_________________________
    btn=Button(Form,text='Save',padx=16,bd=8,fg='black',font=('Arial',12,'bold'),command=save)
    btn_clear=Button(Form,text='Clear',padx=16,bd=8,fg='black',font=('Arial',12,'bold'),command=clear)
    btn.place(x=100,y=460)
    btn_clear.place(x=200,y=460)
    Form.mainloop()
insert()
